### ISSUE TITLE
Proper library

### ISSUE THREAD

**Issue by mplacona** [Nilhcem/ledcontrol-androidthings#1]
Hey @Nilhcem would you be OK if I turned this into a proper library that can be added as a gradle dependency?

**Comment by Nilhcem** [comment]
Thanks for the issue,
You can now import it via

```groovy
dependencies {
    compile 'com.nilhcem.androidthings:driver-max72xx:0.0.1'
}
```

**Comment by mplacona** [comment]
Hey,

Thanks for this. I wasn't sure whether you were gonna get back to me or were even still looking at supporting this library.

I've converted the code into a library with unit tests amd all, but also converted it to Kotlin. I will obviously credit you on it as most of the code for my library was based on the work you and [Digistump](https://github.com/digistump/DigistumpArduino) did.

I'll link you when I'm done
